### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by derekschartung** [cbrianfoley/Logoff-IdleSessions#1]
The reference script name is different from the script name copied over to the scripts folder.

Line 4
    robocopy . C:\Windows\System32\WindowsPowerShell\v1.0\Scripts\ LogOff-IdleSessions.ps1

Line 7
    $Script = "C:\Windows\System32\WindowsPowerShell\v1.0\Scripts\log-off-idle-sessions.ps1"

Line 7 should be
    $Script = "C:\Windows\System32\WindowsPowerShell\v1.0\Scripts\LogOff-IdleSessions.ps1"

**Comment by cbrianfoley** [comment]
Thank you!
